In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from dotenv import load_dotenv
import pandas as pd
from langchain_core.documents import Document
from torch.nn.functional import embedding

In [2]:

load_dotenv()
books =  pd.read_csv("books_cleaned.csv")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,age of books,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,22.0,Gilead,9780002005883:A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,26.0,Spider's Web:A Novel,9780002261982:A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,33.0,Rage of angels,"9780006178736:A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,24.0,The Four Loves,9780006280897:Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,24.0,The Problem of Pain,"9780006280934:""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,23.0,Mistaken Identity,9788172235222:On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,24.0,Journey to the East,9788173031014:This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,23.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623:Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,27.0,I Am that:Talks with Sri Nisargadatta Maharaj,9788185300535:This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,45.0,The Berlin Phenomenology,9789027712059:Since the three volume edition o...

In [3]:
books["tagged_description"]

0       9780002005883:A NOVEL THAT READERS and critics...
1       9780002261982:A new 'Christie for Christmas' -...
2       9780006178736:A memorable, mesmerizing heroine...
3       9780006280897:Lewis' work on the nature of lov...
4       9780006280934:"In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222:On A Train Journey Home To North...
5193    9788173031014:This book tells the tale of a ma...
5194    9788179921623:Wisdom to Create a Life of Passi...
5195    9788185300535:This collection of the timeless ...
5196    9789027712059:Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [4]:
books["tagged_description"].to_csv("tagged_description.txt" , index=False , header = False)

In [5]:
#raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
#text_splitter = CharacterTextSplitter(chunk_size=10000 , chunk_overlap=0 , separator="\n")
#documents = text_splitter.split_documents(raw_documents)
#did not use the character text spliter since the document is already structured as a book per line also the tutorial i follow uses chunk_size=0 which is not suported by the langchain im using in this code
from langchain_core.documents import Document

with open("tagged_description.txt", "r", encoding="utf-8") as f:
    documents = [
        Document(
            page_content=line.strip(),
            metadata={"source": "tagged_description.txt"}
        )
        for line in f
        if line.strip()
    ]

print(len(documents))
print(documents[0])
print(documents[1])

5197
page_content='"9780002005883:A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."' metadata={'source': 'tagged_description.txt'}
page_content='"9780002261982:A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. 'Supposing I were to come down one morning and find a dead body in the library, what should I do?' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI"' metadata={'source': 'tagged_description.txt'}

In [6]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883:A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [8]:

print(len(documents))

print(documents[0])
print(documents[1])
print(documents[2])

5197
page_content='"9780002005883:A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."' metadata={'source': 'tagged_description.txt'}
page_content='"9780002261982:A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. 'Supposing I were to come down one morning and find a dead body in the library, what should I do?' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI"' metadata={'source': 'tagged_description.txt'}
page_content='"9780006178736:A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia's schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power."' metadata={'source': 'tagged_description.txt'}

In [9]:
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db_books = Chroma.from_documents(documents, embedding=embeddings)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [10]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k=10)
docs

[Document(id='24fd3162-bd9d-461f-ac59-03e15577d3ba', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069:Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='ac2d99bd-1fb7-4c93-bfa9-482efd94feec', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380:Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='49e0e6ca-a8f5-48ad-85b9-bcdfe81fb874', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397:Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='c1d46c1f-893b-4250-a4e2-bdd4b1072fe3', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373:Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(id='46af3653-d863-4ba9-81cf-231ad5ec2dbe', metadata={'source': 'tagged_description.txt'}, page_content='"9780060959036:Barbara Kingsolver\'s fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel\'s intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."'),
 Document(id='bade1695-cae2-4037-ab99-a9b07fe4ca1d', metadata={'source': 'tagged_description.txt'}, page_content='"9780374522599:The Control of Nature is John McPhee\'s bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters."'),
 Document(id='60a36f7f-d877-4ed6-a81e-d2ef29505a4f', metadata={'source': 'tagged_description.txt'}, page_content='"9780064402453:‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author\'s father].\' \'BL. 1986 Children\'s Editors\' Choices (BL) Children\'s Choices for 1987 (IRA/CBC) Notable 1986 Childrens\' Trade Books in Social Studies (NCSS/CBC) 1986 Children\'s Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"'),
 Document(id='9e4a82fa-dc8e-4133-b0ba-b21762e05ac3', metadata={'source': 'tagged_description.txt'}, page_content='"9780786819119:Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub."'),
 Document(id='070aa3a2-c0ab-4f19-8014-4f8d8baf1d49', metadata={'source': 'tagged_description.txt'}, page_content='"9780064403870:When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"'),
 Document(id='cddbb3fe-c529-43d3-ab03-ba6b04c8a6e4', metadata={'source': 'tagged_description.txt'}, page_content='"9780802431486:Drawn from years of counseling and the author\'s own parenting experiences, this valuable resource, filled with Scripture passages and accompanying practical applications, provides principles for raising and nurturing children in these uncertain and rapidly changing times. Original."')]

In [13]:
books[books ["isbn13"]==int(docs[0].page_content.split()[0].strip('"').split(":")[0])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,age of books,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,25.0,Baby Einstein: Neighborhood Animals,9780786808069:Children will discover the excit...

In [28]:
def retrieve_sementic_recommendations(
        query: str,
        top_k: int = 10,

) -> pd.DataFrame:
    recs =  db_books.similarity_search(query, k = 50)
    books_list = []
    for i in range(0, len(recs)):
        isbn = int(
            recs[i].page_content.strip('"').split(":")[0])
        books_list.append(isbn)
    #return books[books["isbn13"].isin(books_list)].head(top_k)
    return(books.set_index("isbn13").loc[books_list].head(top_k).reset_index())

In [25]:
retrieve_sementic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,age of books,title_and_subtitle,tagged_description
0,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,25.0,Baby Einstein: Neighborhood Animals,9780786808069:Children will discover the excit...
1,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,24.0,Baby Einstein: Babies,"9780786808380:Introduce your babies to birds, ..."
2,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,24.0,Baby Einstein: Dogs,"9780786808397:Introduce your baby to birds, ca..."
3,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,24.0,Baby Einstein: Birds,"9780786808373:Introducing your baby to birds, ..."
4,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,85440.0,25.0,Prodigal Summer:A Novel,9780060959036:Barbara Kingsolver's fifth novel...
5,9780374522599,0374522596,The Control of Nature,John McPhee,Nature,http://books.google.com/books/content?id=p1qKQ...,The Control of Nature is John McPhee's bestsel...,1990.0,4.24,288.0,3365.0,36.0,The Control of Nature,9780374522599:The Control of Nature is John Mc...
6,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,38.0,Racso and the Rats of NIMH,"9780064402453:‘Racso, a brash and boastful lit..."
7,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,23.0,"Baby Einstein: Water, Water Everywhere",9780786819119:Charming illustrations and playf...
8,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,631.0,35.0,"R-T, Margaret, and the Rats of NIMH",9780064403870:When Margaret and her younger br...
9,9780802431486,0802431488,The 10 Commandments of Parenting,H. Edwin Young,Religion,http://books.google.com/books/content?id=Q1Hxj...,Drawn from years of counseling and the author'...,2005.0,4.00,224.0,25.0,21.0,The 10 Commandments of Parenting:The Do's and ...,9780802431486:Drawn from years of counseling a...
10,9781593851170,1593851170,The Nature of Play,Anthony D. Pellegrini;Peter K. Smith,Psychology,http://books.google.com/books/content?id=Nukz6...,"""Comprehensive and up to date, this tightly ed...",2005.0,4.25,308.0,4.0,21.0,The Nature of Play:Great Apes and Humans,"9781593851170:""Comprehensive and up to date, t..."
11,9780878937202,087893720X,Essentials of Conservation Biology,Richard B. Primack,Science,http://books.google.com/books/content?id=spaGQ...,Essentials of Conservation Biology (Fourth Edi...,2006.0,3.89,585.0,36.0,20.0,Essentials of Conservation Biology,9780878937202:Essentials of Conservation Biolo...
12,9780393959055,0393959058,"Walden ; And, Resistance to Civil Government",Henry David Thoreau,Literary Collections,http://books.google.com/books/content?id=uVxnQ...,The classic chronicle of a communion with natu...,1992.0,3.95,482.0,232.0,34.0,"Walden ; And, Resistance to Civil Government:A...",9780393959055:The classic chronicle of a commu...
13,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,34.0,The Rainbow People,"9780064404419:""Culled from 69 stories collecte..."
14,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,21.0,The Family Way,9780007151240:It should be the most natural th...
15,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,24.0,The Big Box,9780786812912:In her first illustrated book fo...
16,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,27.0,The Deer in the Wood,9780064434980:Even the youngest child can enjo...
17,9781576839546,1576839540,Parenting with Love and Logic,Foster Cline;Jim Fay,Family & Relationships,http://books.google.com/books/content?id=TpCtP...,Cline and Fay offer advice to help parents rai...,2006.0,4.07,271.0,9486.0,20.0,Parenting with Love and Logic:Teaching Childre...,9781576839546:Cline and Fay offer advice to he...
18,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,22.0,Everything on a Waffle,9780374422080:This Newbery Honor Book tells th...
19,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,46.0,"Cry, the Peacock",9788122200850:This book is the story of a youn...

In [30]:
retrieve_sementic_recommendations("A book that teaches math")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,age of books,title_and_subtitle,tagged_description
0,9780747569138,0747569134,More Sideways Arithmetic from Wayside School,Louis Sachar,Arithmetic,http://books.google.com/books/content?id=EMj7H...,Welcome back to maths class at Wayside School....,2004.0,3.92,112.0,839.0,22.0,More Sideways Arithmetic from Wayside School,9780747569138:Welcome back to maths class at W...
1,9780385492249,0385492243,An Invisible Sign of My Own,Aimee Bender,Fiction,http://books.google.com/books/content?id=ZLRKD...,"Mona Gray, a young second grade teacher who or...",2001.0,3.68,256.0,3624.0,25.0,An Invisible Sign of My Own,"9780385492249:Mona Gray, a young second grade ..."
2,9780440241355,0440241359,The Rule of Four,Ian Caldwell;Dustin Thomason,Fiction,http://books.google.com/books/content?id=KAtIT...,Trying to decipher an ancient text that weaves...,2005.0,3.22,450.0,24001.0,21.0,The Rule of Four,9780440241355:Trying to decipher an ancient te...
3,9780870610639,0870610635,Summa Theologica,Thomas Aquinas,"Theology, Doctrinal",http://books.google.com/books/content?id=l9R4x...,Creating a summary of all human knowledge may ...,2000.0,4.10,3020.0,2673.0,26.0,Summa Theologica:Complete 5-Volume Set,9780870610639:Creating a summary of all human ...
4,9780099928409,009992840X,Ratner's Star,Don DeLillo,Life on other planets,http://books.google.com/books/content?id=GTJAN...,Billy Twillig has won the first Nobel Prize ev...,1976.0,3.49,448.0,1478.0,50.0,Ratner's Star,9780099928409:Billy Twillig has won the first ...
5,9780747569121,0747569126,Sideways Arithmetic from Wayside School,Louis Sachar,Arithmetic,http://books.google.com/books/content?id=-oViP...,These Sideways Arithmetic problems may look pu...,2004.0,3.87,96.0,3627.0,22.0,Sideways Arithmetic from Wayside School,9780747569121:These Sideways Arithmetic proble...
6,9780691050843,0691050848,The Nature of Space and Time,Stephen Hawking;Roger Penrose,Science,http://books.google.com/books/content?id=LstaQ...,Presents a series of lectures delivered in 199...,2000.0,4.09,152.0,945.0,26.0,The Nature of Space and Time,9780691050843:Presents a series of lectures de...
7,9780439569729,0439569729,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),Terry Cooper,Education,http://books.google.com/books/content?id=b-EBH...,"416 bright, colorful pages that give kids prac...",2003.0,4.57,416.0,7.0,23.0,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),"9780439569729:416 bright, colorful pages that ..."
8,9780131871656,013187165X,Astronomy,Eric Chaisson;Stephen McMillan,Mathematics,http://books.google.com/books/content?id=1O00A...,This introduction to astronomy features an exc...,2006.0,3.85,499.0,153.0,20.0,Astronomy:a beginner's guide to the universe,9780131871656:This introduction to astronomy f...
9,9780762419227,0762419229,God Created The Integers,Stephen Hawking,Mathematics,http://books.google.com/books/content?id=3zdFS...,Looks at landmark mathematical discoveries ove...,2005.0,4.06,1160.0,1650.0,21.0,God Created The Integers,9780762419227:Looks at landmark mathematical d...

In [32]:
retrieve_sementic_recommendations("a book that helps with mental health ")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,age of books,title_and_subtitle,tagged_description
0,9780330346511,0330346512,An Unquiet Mind,Kay Redfield Jamison,Biography & Autobiography,http://books.google.com/books/content?id=adEqu...,"In this book, a world authority on manic-depre...",1997.0,4.05,240.0,297.0,29.0,An Unquiet Mind:A Memoir of Moods and Madness,"9780330346511:In this book, a world authority ..."
1,9780684854670,0684854678,The Noonday Demon,Andrew Solomon,Psychology,http://books.google.com/books/content?id=ZgbbA...,Winner of the National Book Award and a Pulitz...,2002.0,4.17,576.0,8749.0,24.0,The Noonday Demon:An Atlas of Depression,9780684854670:Winner of the National Book Awar...
2,9780451160317,0451160312,I Never Promised You a Rose Garden,Joanne Greenberg,Mental illness,http://books.google.com/books/content?id=I2R1x...,Chronicles the three-year battle of a mentally...,1989.0,3.86,288.0,23725.0,37.0,I Never Promised You a Rose Garden,9780451160317:Chronicles the three-year battle...
3,9780195135794,0195135792,Manic-Depressive Illness,Frederick K. Goodwin;Kay Redfield Jamison,Medical,http://books.google.com/books/content?id=hOHWE...,This long-awaited second edition of Manic-Depr...,2007.0,4.39,1262.0,103.0,19.0,Manic-Depressive Illness:Bipolar Disorders and...,9780195135794:This long-awaited second edition...
4,9781573229623,1573229628,Prozac Nation,Elizabeth Wurtzel,Biography & Autobiography,http://books.google.com/books/content?id=441Xv...,"A memoir of sex, drugs, and depression indicts...",2002.0,3.59,384.0,875.0,24.0,Prozac Nation:Young and Depressed in America,"9781573229623:A memoir of sex, drugs, and depr..."
5,9780345487421,0345487427,Feel the Fear-- and Do it Anyway,Susan J. Jeffers,Psychology,http://books.google.com/books/content?id=o2Wbc...,A psychotherapist shows how to identify the fe...,2007.0,4.03,217.0,474.0,19.0,Feel the Fear-- and Do it Anyway,9780345487421:A psychotherapist shows how to i...
6,9780452281325,0452281326,The Feeling Good Handbook,David D. Burns,Psychology,http://books.google.com/books/content?id=akVIQ...,"Discusses how to overcome fears, phobias, and ...",1999.0,4.00,729.0,4666.0,27.0,The Feeling Good Handbook,"9780452281325:Discusses how to overcome fears,..."
7,9780316578998,0316578991,The Black Veil,Rick Moody,Family & Relationships,http://books.google.com/books/content?id=AQC2Q...,The author weaves together past and present an...,2002.0,3.06,336.0,391.0,24.0,The Black Veil:A Memoir with Digressions,9780316578998:The author weaves together past ...
8,9780781731836,0781731836,Kaplan & Sadock's Synopsis of Psychiatry,Benjamin J. Sadock;Virginia A. Sadock,Medical,http://books.google.com/books/content?id=YX5mQ...,The best-selling general psychiatry text since...,2003.0,4.20,1500.0,236.0,23.0,Kaplan & Sadock's Synopsis of Psychiatry:Behav...,9780781731836:The best-selling general psychia...
9,9780684831831,068483183X,Touched With Fire,Kay Redfield Jamison,Psychology,http://books.google.com/books/content?id=265d7...,The definitive work on the profound and surpri...,1996.0,4.01,384.0,4087.0,30.0,Touched With Fire,9780684831831:The definitive work on the profo...